APT::FTPArchive::Release::Origin "apt-bundle";
APT::FTPArchive::Release::Label "apt-bundle";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64 arm64 armhf i386";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "apt-bundle APT repository";
