package commands

import (
	"fmt"
	"sort"
	"time"

	"github.com/apt-bundle/apt-bundle/internal/apt"
	"github.com/spf13/cobra"
)

var dumpCmd = &cobra.Command{
	Use:   "dump",
	Short: "Generate an Aptfile from the current system state",
	Long: `Dump generates an Aptfile by listing all manually installed packages
and custom PPAs and repositories from the system.

For repositories managed by apt-bundle that use Signed-By (GPG keys), the
corresponding key directive is emitted automatically when the key was downloaded
by apt-bundle (which stores the original URL alongside the key file).

For repositories added by other tools or older versions of apt-bundle, the key
directive may not be available; in that case only the deb line is emitted and
you may need to add the key directive manually.`,
	RunE: runDump,
}

func init() {
	rootCmd.AddCommand(dumpCmd)
}

func runDump(cmd *cobra.Command, args []string) error {
	w := cmd.OutOrStdout()

	fmt.Fprintln(w, "# Aptfile generated by apt-bundle dump")
	fmt.Fprintln(w, "# Generated on:", getCurrentTime())
	fmt.Fprintln(w)

	fmt.Fprintln(w, "# --- Packages ---")
	packages, err := mgr.GetAllInstalledPackages()
	if err != nil {
		return fmt.Errorf("failed to list installed packages: %w", err)
	}

	sort.Strings(packages)
	for _, pkg := range packages {
		fmt.Fprintln(w, "apt", pkg)
	}

	// Emit custom repositories (PPAs and deb) from sources.list and sources.list.d
	sources, err := apt.ListCustomSources(apt.SourcesListPath, apt.SourcesDir)
	if err != nil {
		return fmt.Errorf("failed to list custom sources: %w", err)
	}
	if len(sources) > 0 {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "# --- Repositories ---")
		for _, e := range sources {
			if e.KeyURL != "" {
				fmt.Fprintln(w, "key", e.KeyURL)
			}
			fmt.Fprintln(w, e.AptfileLine)
		}
	}

	return nil
}

func getCurrentTime() string {
	return time.Now().Format("2006-01-02 15:04:05")
}
