package commands

import (
	"bytes"
	"errors"
	"os"
	"strings"
	"testing"

	"github.com/apt-bundle/apt-bundle/internal/apt"
	"github.com/apt-bundle/apt-bundle/internal/testutil"
)

func TestRunDump(t *testing.T) {
	t.Run("emits header and sorted apt lines", func(t *testing.T) {
		mock := testutil.NewMockExecutor()
		mock.OutputFunc = func(name string, args ...string) ([]byte, error) {
			if name == "apt-mark" && len(args) > 0 && args[0] == "showmanual" {
				return []byte("vim\ncurl\ngit\n"), nil
			}
			return nil, errors.New("unexpected command")
		}
		apt.SetExecutor(mock)
		defer apt.ResetExecutor()

		old := os.Stdout
		r, w, _ := os.Pipe()
		os.Stdout = w
		defer func() { os.Stdout = old }()

		err := runDump(dumpCmd, []string{})
		if err != nil {
			t.Fatalf("runDump: %v", err)
		}

		_ = w.Close()
		var buf bytes.Buffer
		_, _ = buf.ReadFrom(r)
		os.Stdout = old
		out := buf.String()

		if !strings.Contains(out, "# Aptfile generated by apt-bundle dump") {
			t.Error("output should contain dump header")
		}
		if !strings.Contains(out, "# --- Packages ---") {
			t.Error("output should contain Packages section comment")
		}
		if !strings.Contains(out, "apt curl") {
			t.Error("output should contain 'apt curl'")
		}
		if !strings.Contains(out, "apt git") {
			t.Error("output should contain 'apt git'")
		}
		if !strings.Contains(out, "apt vim") {
			t.Error("output should contain 'apt vim'")
		}
		// Sorted order: curl, git, vim
		curlIdx := strings.Index(out, "apt curl")
		gitIdx := strings.Index(out, "apt git")
		vimIdx := strings.Index(out, "apt vim")
		if curlIdx > gitIdx || gitIdx > vimIdx {
			t.Errorf("packages should be sorted: curl < git < vim, got positions curl=%d git=%d vim=%d", curlIdx, gitIdx, vimIdx)
		}
	})

	t.Run("returns error when GetAllInstalledPackages fails", func(t *testing.T) {
		mock := testutil.NewMockExecutor()
		mock.OutputFunc = func(name string, args ...string) ([]byte, error) {
			if name == "apt-mark" {
				return nil, errors.New("apt-mark failed")
			}
			return nil, nil
		}
		apt.SetExecutor(mock)
		defer apt.ResetExecutor()

		err := runDump(dumpCmd, []string{})
		if err == nil {
			t.Error("runDump should return error when apt-mark fails")
		}
	})
}
