package commands

import (
	"fmt"
	"time"

	"github.com/spf13/cobra"
)

var dumpCmd = &cobra.Command{
	Use:   "dump",
	Short: "Generate an Aptfile from the current system state",
	Long: `Dump generates an Aptfile by listing all manually installed packages
and optionally custom PPAs and repositories from the system.`,
	RunE: runDump,
}

func init() {
	rootCmd.AddCommand(dumpCmd)
}

func runDump(cmd *cobra.Command, args []string) error {
	fmt.Println("# Aptfile generated by apt-bundle dump")
	fmt.Println("# Generated on:", getCurrentTime())
	fmt.Println()

	// TODO: Implement the actual dump logic
	// 1. Query manually installed packages using apt-mark
	// 2. List custom repositories from /etc/apt/sources.list.d/
	// 3. Format and output as Aptfile directives

	return nil
}

func getCurrentTime() string {
	return time.Now().Format("2006-01-02 15:04:05")
}
